global:
  domain: ""

configs:
  cm:
    # Reconciliation intervals
    timeout.reconciliation: 5s
    timeout.reconciliation.jitter: 0s

server:
  service:
    type: ClusterIP
  extraArgs:
    - --insecure

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true


